name: ${project.name}
main: com.bergerkiller.bukkit.lightcleaner.LightCleaner
api-version: 1.13
version: ${project.version}
build: ${project.build.number}
authors: [bergerkiller]
depend: [BKCommonLib]
softdepend: [WorldEdit]
description: Cleans up bugged lighting in chunks or entire worlds
dev-url: ${project.url}
commands:
    cleanlight:
        description: Cleans up bugged lighting in chunks or entire worlds
        usage: |
          /cleanlight
          /cleanlight [chunk_radius]
          /cleanlight world [world_name]
          /cleanlight abort
          /cleanlight status
