name: ${project.name}
dev-url: ${project.url}
version: ${project.version}
build: ${project.build.number}
description: Cleans up bugged lighting in chunks or entire worlds
authors: [bergerkiller]
softdepend: [BKCommonLib, WorldEdit]
api-version: 1.13

main: com.bergerkiller.bukkit.lightcleaner.Preloader
preloader:
    main: com.bergerkiller.bukkit.lightcleaner.LightCleaner
    depend:
        BKCommonLib: https://www.spigotmc.org/resources/bkcommonlib.39590/

commands:
    cleanlight:
        description: Cleans up bugged lighting in chunks or entire worlds
        usage: |
          /cleanlight
          /cleanlight [chunk_radius]
          /cleanlight world [world_name]
          /cleanlight abort
          /cleanlight status
